// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	"net/http"

	"github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: method, path, handler
func (_m *Handler) Handle(method string, path string, handler http.Handler) {
	_m.Called(method, path, handler)
}

// ServeHTTP provides a mock function with given fields: _a0, _a1
func (_m *Handler) ServeHTTP(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}
